class exception{
	public static void main(String args[])
	{
	 try{
	 	int a=2,b=5,c=2,x=7,z;
	 	int p[]={3};
	 	//p[2]=33;
	 	try{
	 		z=x/((b*b)-(4*a*c));
	 		System.out.println("Z = "+z);
	 	    }
	 	   catch(ArithmeticException e){
	 	   System.out.println("Division by Zero");
	 	   }
	    }
	    
	    catch(ArrayIndexOutOfBoundsException e)
	    {
	    System.out.println("Array Indexes Out Of Bounds");
	    }
	 }
}
